### ISSUE TITLE
How to defrag etcd 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#1016]

**Comment by MBishop17** [comment]
Add to RKE docs. What it sounds like. @guangbochen will know the commands.

**Comment by catherineluse** [comment]
I saw that we have some documentation about defragging etcd already: https://rancher.com/docs/rancher/v2.x/en/troubleshooting/kubernetes-components/etcd/#defrag-all-etcd-members

@deniseschannon Do the commands in that section apply to this issue?

Also, I wonder if the troubleshooting for Kubernetes components should be moved to the RKE docs, and then the Rancher troubleshooting section would link to that.

**Comment by catherineluse** [comment]
Closing this issue because it has been documented

**Comment by ebuildy** [comment]
My 2 cents, a simple pod that executes all docker exec commands:

```
apiVersion: v1 
kind: Pod 
metadata: 
    name: dood 
spec: 
    containers: 
      - name: docker-cmds 
        image: docker:1.12.6 
        command:
        - docker
        - exec
        - etcd
        - sh
        - -c
        - |
          export ETCDCTL_ENDPOINTS=$(etcdctl member list | cut -d, -f5 | sed -e 's/ //g' | paste -sd ',')
          etcdctl defrag
        resources: 
            requests: 
                cpu: 10m 
                memory: 256Mi 
        volumeMounts: 
          - mountPath: /var/run 
            name: docker-sock 
    volumes: 
      - name: docker-sock 
        hostPath: 
            path: /var/run
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchFields:
                - key: metadata.name
                  operator: In
                  values:
                    - XXXXX
    nodeName: XXXXXX
    tolerations:
    - operator: Exists
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
    - key: node.kubernetes.io/disk-pressure
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/pid-pressure
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/unschedulable
      operator: Exists
      effect: NoSchedule
    - key: node.kubernetes.io/network-unavailable
      operator: Exists
      effect: NoSchedule
```
