### ISSUE TITLE
Markdown Files for Security Benchmarks/Hardening

### ISSUE THREAD

**Issue by JJediny** [rancher/docs#1157]
https://releases.rancher.com/documents/security/latest/Rancher_Hardening_Guide.pdf
https://releases.rancher.com/documents/security/latest/Rancher_Benchmark_Assessment.pdf

Sorry to file an issue for this but searching for them hasn't worked. Are the markdown files for these documents available? Each pdf indicates there was a .md file they were generated from.

**Comment by deniseschannon** [comment]
Yes, they exist here: https://rancher.com/docs/rancher/v2.x/en/faq/security/

**Comment by cloudnautique** [comment]
They live in a private repo with someother docs. 

Is there something you need from them? We could probably move the published versions md into the docs directly.

**Comment by JJediny** [comment]
Yes I'm trying to develop some inspec test to verify these best practices, it would be great to have them published in MD

**Comment by segonz-dev** [comment]
Could it be possible to make public available the YAML from the Appendix A on the Hardening Guide? It's difficult to copy/paste the cluster.yml recommendations without introducing typing errors.

**Comment by ChrisMcKee** [comment]
Out of interest has anyone tried spinning up a new cluster using the settings in this guide?
```yaml
kubernetes_version: v1.13.4-rancher1-1
cluster_name: rancher-k8

nodes:
  - address: ${node_one_ip} # hostname or IP to access nodes
    user: ubuntu # root user (usually 'root')
    role: [controlplane, worker, etcd] # K8s roles for node
    ssh_key_path: ./sshkey # path to PEM file
  - address: ${node_two_ip}
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: ./sshkey
  - address: ${node_three_ip}
    user: ubuntu
    role: [controlplane, worker, etcd]
    ssh_key_path: ./sshkey
ignore_docker_version: true

cloud_provider:
    name: aws

network:
    plugin: canal

ingress:
    provider: nginx

services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h0s # time increment between snapshots
    retention: 168h # time increment before snapshot purge
  kubelet:
    extra_args:
      streaming-connection-idle-timeout: "1800s"
      protect-kernel-defaults: "true"
      make-iptables-util-chains: "true"
      event-qps: "0"
  kube-api:
    pod_security_policy: false
    extra_args:
      anonymous-auth: "false"
      profiling: "false"
      repair-malformed-updates: "false"
      service-account-lookup: "true"
      enable-admission-plugins: "ServiceAccount,NamespaceLifecycle,LimitRanger,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,AlwaysPullImages,DenyEscalatingExec,NodeRestriction,EventRateLimit,PodSecurityPolicy"
      admission-control-config-file: "/etc/kubernetes/admission.yaml"
      encryption-provider-config: /etc/kubernetes/encryption.yaml
      audit-log-path: "/var/log/kube-audit/audit-log.json"
      audit-log-maxage: "5"
      audit-log-maxbackup: "5"
      audit-log-maxsize: "100"
      audit-log-format: "json"
      audit-policy-file: /etc/kubernetes/audit.yaml
    extra_binds:
      - "/var/log/kube-audit:/var/log/kube-audit"
  scheduler:
    extra_args:
      profiling: "false"
      address: "127.0.0.1"
  kube-controller:
    extra_args:
      profiling: "false"
      address: "127.0.0.1"
      terminated-pod-gc-threshold: "1000"

addons: |
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: default-psp-role
    namespace: ingress-nginx
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - default-psp
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: default-psp-rolebinding
    namespace: ingress-nginx
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: default-psp-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
  ---
  apiVersion: v1
  kind: Namespace
  metadata:
    name: cattle-system
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: default-psp-role
    namespace: cattle-system
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - default-psp
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: default-psp-rolebinding
    namespace: cattle-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: default-psp-role
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
  ---
  apiVersion: extensions/v1beta1
  kind: PodSecurityPolicy
  metadata:
    name: restricted
  spec:
    requiredDropCapabilities:
    - NET_RAW
    privileged: false
    allowPrivilegeEscalation: false
    defaultAllowPrivilegeEscalation: false
    fsGroup:
      rule: RunAsAny
    runAsUser:
      rule: MustRunAsNonRoot
    seLinux:
      rule: RunAsAny
    supplementalGroups:
      rule: RunAsAny
    volumes:
    - emptyDir
    - secret
    - persistentVolumeClaim
    - downwardAPI
    - configMap
    - projected
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: psp:restricted
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - restricted
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: psp:restricted
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: psp:restricted
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
```

Not had much luck myself
