### ISSUE TITLE
Document rancher metrics endpoint

### ISSUE THREAD

**Issue by daxmc99** [rancher/docs#1561]
Rancher has a metrics endpoint that can provide information to a Prometheus instance which allows for fine-grain information about Rancher. This information allows for more observability into Rancher. 
See https://github.com/rancher/rancher/issues/20341

We should document how to set this up and a brief description of all the fields exposed.

Prometheus config:
```
scrape_configs:
     - job_name: rancher
      scheme: https
      bearer_token: {{ rancher_metrics_token.stdout }}
      scrape_interval: 15s
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - action: keep
        regex: cattle-system;cattle;cattle-server;443
        source_labels:
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_label_app
        - __meta_kubernetes_pod_label_component
        - __meta_kubernetes_pod_container_port_number
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
```
