### ISSUE TITLE
Document steps to set a proxy for imported cluster agents

### ISSUE THREAD

**Issue by bmdepesa** [rancher/docs#2286]
Currently there are no documented steps on how to specify a proxy for the cluster/node agents in an imported cluster. 

Steps are: 
 * Add Cluster > Import an existing cluster > Create
* Download the yaml specified in the command
* Edit the yaml to add the proxy environment variables to both the cluster agent deployment and node agent daemonset:
```
env:
- name: CATTLE_SERVER
  value: "https://rancher.url"
- name: CATTLE_CA_CHECKSUM
  value: "8885a3b0ad0a89a8cf98b069614589cd8729be28c967c660ad3bba30e97e7af7"
- name: CATTLE_CLUSTER
  value: "true"
- name: CATTLE_K8S_MANAGED
  value: "true"
- name: HTTP_PROXY
  value: "proxy.url:3128"
- name: HTTPS_PROXY
  value: "proxy.url:3128"
- name: NO_PROXY
  value: "localhost,127.0.0.1,0.0.0.0"
```
* Run `kubectl apply` with the locally modified file: `kubectl apply -f cluster-import.yaml`
* The cluster will register and the agents will be using the specified proxy.
