### ISSUE TITLE
Permissive allow all on v2.3.5 hardening guide incorrect

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#2333]
Permissive allow all NetworkPolicy on v2.3.5 hardening guide is incorrect at the following link.
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#ensure-that-all-namespaces-have-network-policies-defined

Example of deny all policy which we have in the above link
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-all
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
```

Example of allow all policy:
```
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-allow-all
spec:
  podSelector: {}
  egress:
  - {}
  ingress:
  - {}
  policyTypes:
  - Ingress
  - Egress
```

I have tested both of the above.  If you apply the deny all policy to all namespaces, it will break Rancher communication with the kube-apiserver as well as user workloads.
