### ISSUE TITLE
Issue in Hardening guide for CIS v1.5

### ISSUE THREAD

**Issue by sowmyav27** [rancher/docs#2349]
**Page:** 
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/

**Issue#1**
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#reference-hardened-rke-cluster-yml-configuration
- `generate_serving_certificate: true` appears twice in this section. 
```
kubelet:
    generate_serving_certificate: true
    extra_args:
      feature-gates: "RotateKubeletServerCertificate=true"
      protect-kernel-defaults: "true"
      tls-cipher-suites: "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
    extra_binds: []
    extra_env: []
    cluster_domain: ""
    infra_container_image: ""
    cluster_dns_server: ""
    fail_swap_on: false
    generate_serving_certificate: true
```

**Issue#2**
Script here has to be fixed - https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#ensure-that-all-namespaces-have-network-policies-defined
