### ISSUE TITLE
Issues in RKE CIS 1.4 and 1.5 hardening guide

### ISSUE THREAD

**Issue by sowmyav27** [rancher/docs#2368]
1. In this cluster.yml file: https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#reference-hardened-rke-cluster-yml-configuration
**Actual:**
```
# If you intend to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
kubernetes_version: "v1.15.9-rancher1-1"
enable_network_policy: true
default_pod_security_policy_template_id: "restricted"
```

**Expected:**
```
# If you intend to deploy Kubernetes in an air-gapped environment,
# please consult the documentation on how to configure custom RKE images.
default_pod_security_policy_template_id: "restricted"
enable_network_policy: true
rancher_kubernetes_engine_config:
  kubernetes_version: "v1.15.9-rancher1-1"
```

2. In this rke template: https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3/#appendix-c-complete-rke-template-example 

**Actual:**
```
#
# Cluster Config
#
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
#
# Rancher Config
#
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  ignore_docker_version: true
```

**Expected:**
```
#
# Cluster Config
#
docker_root_dir: /var/lib/docker
enable_cluster_alerting: false
enable_cluster_monitoring: false
enable_network_policy: false
default_pod_security_policy_template_id: "restricted"
#
# Rancher Config
#
rancher_kubernetes_engine_config:
  addon_job_timeout: 30
  ignore_docker_version: true
```
- Also the following if present in the yaml file in kube-apiserver params, cluster fails to come up
1. extra_binds:
      - "/var/log/kube-audit:/var/log/kube-audit"
2. audit-policy-file: /opt/kubernetes/audit.yaml
3. admission-control-config-file: /opt/kubernetes/admission.yaml
