### ISSUE TITLE
vSphere cloud provider docs are not clear

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#2629]
The following are instructions we've come up with to help clarify, but there are a lot of interlinked documents.  Is this the best place to put them: https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/

The following prereq & steps need to be performed before adding the Vmware Storage to the Cluster:

1. Make sure your node's hostnames are in lower case (eg:host1) in vCenter. We've seen an issue where Vmware failed to recognize hosts and connect when hostnames included capital letters (eg:HOST1)
2. Check the Connectivity between rancher downstream cluster to Vcenter server with the given Vcenter credentials and DC details.  The following test should be run on a downstream cluster node:
    1. On the downstream node, download and configure govc:
        ```
        $ curl -L <https://github.com/vmware/govmomi/releases/download/v0.22.1/govc_linux_amd64.gz> | gunzip > /usr/local/bin/govc
        $ chmod +x /usr/local/bin/govc
        $ cat >set_vc_params.sh<<EOF
        read -p "User Name: " VC_USR
        read -s -p "Password: " VC_PASSWD && echo
        read -p "VC URL (<https://VC_FQDN):> " VC_FQDN
        read -p "DC Name: " DC_NAME
        export GOVC_USERNAME="${VC_USR}"
        export GOVC_INSECURE=1
        export GOVC_PASSWORD="${VC_PASSWD}"
        export GOVC_URL="${VC_FQDN}"
        export DATACENTER="${DC_NAME}"
        EOF
        $ source set_vc_params.sh
        ```
    2. Check the connectivity by listing the VMs  
    `$ govc ls "/$DATACENTER/vm/"`
3. If connectivity checks pass, follow the two VMWare prerequisit and installation documents:
- https://vsphere-csi-driver.sigs.k8s.io/driver-deployment/prerequisites.html
- https://vsphere-csi-driver.sigs.k8s.io/driver-deployment/installation.html
4.  Check that the drivers are successfully installed by running:
  `kubectl describe csidrivers`
5. If drivers were successfully installed, add the Vmware details to your cluster config YAML (in the following format) and save/`rke up`:
    ```
    cloud_provider:
      name: vsphere
      vsphereCloudProvider:
        disk: {}
        global:
          insecure-flag: true
          soap-roundtrip-count: 0
        network: {}
        virtual_center:
          xxxx.com:
            datacenters: /xxxx
            soap-roundtrip-count: 0
            user: user@vsphere.local
            password: PASSWORD
        workspace:
          datacenter: /xxxx
          default-datastore: /xxxx/datastore/xxxx
          folder: /xxxx/vm
          server: xxxx.com
    ```
    If you see any permission denied message check that your user has admin privileges, or create one that Rancher can use to manipulate vSphere resources (see: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/vsphere/provisioning-vsphere-clusters/creating-credentials/)
If you still see issues, you may need to use the superuser credentials (eg. administrator@vsphere.local).

**NOTE**: If you already have nodes in this cluster, it's important to manually patch the nodes. Follow the instructions in the following VMWare doc to update the node providerID fields (you may need to modify the script according to your environment before running):
    https://vmware.github.io/vsphere-storage-for-kubernetes/documentation/existing.html#update-all-node-providerid-fields

 You should now be able to see the VMWare provider in the Provisioner drop down when creating a new storage class (see: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/examples/vsphere/)
