### ISSUE TITLE
[Monitoring V2] Add docs for persisting Grafana Dashboards

### ISSUE THREAD

**Issue by aiyengar2** [rancher/docs#2805]
We need to document the flow of users persisting Grafana Dashboards by:
1. Using the Grafana UI to create a dashboard (but no need to click on save): https://grafana.com/docs/grafana/latest/getting-started/getting-started/#step-3-create-a-dashboard. 
    - Note: they will need to be logged into Grafana to create dashboards since the default anonymous user is only a Viewer
2. Copying the JSON from `View JSON` on the created Dashboard: https://grafana.com/docs/grafana/latest/dashboards/json-model/
3. Pasting the JSON to a ConfigMap that is within the `cattle-dashboards` namespace and has the label `grafana_dashboard: 1` and saving the ConfigMap

Once they have created this ConfigMap, it should show up on the Grafana UI and be persisted even if the Grafana pod is restarted. 

We should also note that, if they are using Persistent Volumes, they can just save the dashboard directly via the Grafana UI if they are a user with enough permissions on Grafana to do so (e.g. admin), but it is recommended to use ConfigMaps instead since that can be copied across multiple clusters and can be deployed with a GitOps or CD based approach that allows dashboards to be put under version control.

#### Example ConfigMap produced

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_dashboard: "1"
  name: <dashboard-name>
  namespace: cattle-dashboards
data:
  <dashboard-name>.json: |-
    <copied-json>
```
