### ISSUE TITLE
[Rancher2] Deploy RKE cluster using flatcar linux OS

### ISSUE THREAD

**Issue by sowmyav27** [rancher/docs#2874]
**Request Summary:**
To deploy an RKE cluster (downnstream/HA cluster) using `flatcar-linux-stable-2605.6.0` OS instances, the cluster.yml should be configured like
```
# rancher-cluster.yml 
# cluster 1
nodes:
  - address:
    internal_address: 
    user: core
    role: [etcd, controlplane, worker]   
    ssh_key_path:  

network:
  plugin: calico
  options:
    calico_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
    flannel_backend_type: vxlan
 
services:
  kube-controller:
    extra_args:
      flex-volume-plugin-dir: /opt/kubernetes/kubelet-plugins/volume/exec/
```

```
# rancher-cluster.yml 
# cluster 2
nodes:
  - address:
    internal_address: 
    user: core
    role: [etcd, controlplane, worker]   
    ssh_key_path:  

network:
  plugin: canal
  options:
    canal_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds
    flannel_backend_type: vxlan
 
services:
  kube-controller:
    extra_args:
      flex-volume-plugin-dir: /opt/kubernetes/kubelet-plugins/volume/exec/
```
Without this in the cluster.yml, the cluster fails to come up. Related issue - https://github.com/rancher/rancher/issues/29841
