### ISSUE TITLE
[Rancher2] Update README for backup regarding the S3 backup secret

### ISSUE THREAD

**Issue by gaktive** [rancher/docs#3054]
**Request Summary:**
Based on feedback on Rancher 2.5.3, the README should be updated for backups regarding the S3 backup secret. We should be clearer as to what namespace needs to have the S3 backup secret created in.

**Details:**
Currently, the user has to go look at the Helm README to figure out where the chart will be installed, but that namespace doesn’t exist. It ultimately doesn’t appear to matter but having guidance on where to put it would help instill confidence in the user.

**Comment by catherineluse** [comment]
Sowmya said the backup restore app uses the `credentialSecretNamespace` to determine where to look for the S3 backup secret:

```
s3:
  bucketName: ''
  credentialSecretName: ''
  credentialSecretNamespace: ''
  enabled: false
  endpoint: ''
  endpointCA: ''
  folder: ''
  insecureTLSSkipVerify: false
  region: ''
```
When deploying the app through the dashboard UI, the Credential Secret dropdown lists the secrets in all the namespaces. 

I'll update the docs to reflect this and submit a PR to update the README.
