### ISSUE TITLE
[Rancher2] 

### ISSUE THREAD

**Issue by paulchoi** [rancher/docs#3079]
**Request Summary:**

Clarify that the `s3-creds` Secret resource needs base64-encoded access key and secret key. While it's normally expected that the data in a Secret resource should be base64-encoded, it's easy to miss that detail. Please make it more obvious.

In https://github.com/rancher/docs/blob/master/content/rancher/v2.x/en/backups/v2.5/migrating-rancher/_index.md

**Details:**

Change as such:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: s3-creds
type: Opaque
data:
  accessKey: <Enter your base64-encoded access key>
  secretKey: <Enter your base64-encoded secret key>
```
