### ISSUE TITLE
[Rancher2] Monitoring V2 - Add docs for Windows cluster support

### ISSUE THREAD

**Issue by aiyengar2** [rancher/docs#3113]
**Request Summary:**

Add docs describing the requirements for Windows clusters to deploy Monitoring V2

**Details:**

### Summary

Starting at Monitoring V2 9.4.204 (Rancher 2.5.8), Monitoring V2 can now be deployed on a Windows cluster and will scrape Windows nodes using https://github.com/prometheus-community/windows_exporter (a community project previously named `wmi_exporter` when deployed in Monitoring V1).

### Comparison to Monitoring V1

Unlike Monitoring V1 for Windows, metrics collected by windows_exporter will be labeled as `windows_` instead of `wmi_` in accordance to a naming change from upstream from wmi_exporter to windows_exporter.

In addition, Monitoring V2 for Windows will leverage a new feature in `wins` v0.1.0 to support scraping `windows_exporter` metrics from the Pod itself rather than from the Node. This means that users will no longer have to keep port 9796 open on each Windows host to allow Prometheus to scrape metrics.

### Cluster Requirements

Monitoring V2 for Windows can only scrape metrics from Windows hosts that have a minimum `wins` version of v0.1.0.  To be able to fully deploy Monitoring V2 for Windows, **all** of your hosts must meet this requirement.

If you provision a *fresh* cluster in Rancher 2.5.8, your cluster should already meet this requirement.

#### Upgrading Existing Clusters to wins v0.1.0

If the cluster was provisioned before Rancher 2.5.8 (even if the current Rancher version is 2.5.8), you will not be able to successfully deploy Monitoring V2 for Windows until you upgrade the wins version on each host to at least v0.1.0.

To facilitate this upgrade, Rancher 2.5.8 has released a brand new Helm chart called `rancher-wins-upgrader`. 

To upgrade your hosts on an existing Windows cluster, uninstall Monitoring V1 for Windows and then simply deploy `rancher-windows-upgrader` with the following override:

```yaml
# Masquerading bootstraps the wins-upgrader installation via a previously white-listed process path since the normal install path, c:\etc\rancher\wins\wins-upgrade.exe is not normally whitelisted. In this case, we are using the previously white-listed process path used by Monitoring V1.
masquerade:
  enabled: true
  as: c:\\etc\wmi-exporter\wmi-exporter.exe
```

Note: If you set up the RKE cluster with a `cluster.yml` that has a non-default `win_prefix_path`, you will need to update the `masquerade.as` field with your prefix path in place of `c:\\`. For example, if you have `win_prefix_path: 'c:\host\opt\'`, then you will need to set `as: c:\host\opt\etc\wmi-exporter\wmi-exporter.exe`.

Once all your hosts have been successfully upgraded, please ensure that you deploy the Helm chart once again with default values to avoid conflicts with :
```yaml
masquerade:
  enabled: false
```

Once complete, you may choose to uninstall the `rancher-wins-upgrader` chart or keep it in your cluster to facilitate future upgrades. For more information on how it can be used, please see the [README.md](https://github.com/rancher/wins/blob/master/charts/rancher-wins-upgrader/README.md) of the chart.
