### ISSUE TITLE
[Rancher2]  Update add-ons documentation to include priority class name

### ISSUE THREAD

**Issue by slickwarren** [rancher/docs#3122]
**Request Summary:**
There is now the option to change priority class name of add ons.  Please include that in [our docs](https://rancher.com/docs/rke/latest/en/config-options/add-ons/).  
we would need to update the following:
* ingress, metrics-server, coredns, kube_dns, nodelocal, canal, calico, flannel, weave

**Details:**

* DNS and Network plug-ins have the field under `options` when defined. I.e.
```
dns:
    options:
      kube_dns_autoscaler_priority_class_name: system-cluster-critical
      kube_dns_priority_class_name: system-cluster-critical
    provider: kube-dns
```
* whereas metrics-server and ingress are defined in the add on itself
```
monitoring:
  provider: metrics-server
  metrics_server_priority_class_name: system-cluster-critical
```
* this is the priorityClassName in k8s
* any new field would follow the format `<addon_workload_name>_priority_class_name`
