### ISSUE TITLE
Update docs about using Istio with RKE2 and SELinux

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3286]
This page needs to be updated: https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/configuration-reference/rke2/

The original doc issue is https://github.com/rancher/docs/issues/2877

This CNI configuration:

```
cni:
      image: rancher/istio-install-cni:1.7.3
```

would need to be updated in the overlay that you are applying to whatever version of istio you are using, and starting in 1.7.8/1.8.3 we are using rancher/mirrored-istio-install-cni:1.8.3  format. This could be an problem if you are trying to use an older version of cni with a newer istio

This configuration worked for Mitchell with Istio version 1.9.500:

```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  components:
    cni:
      enabled: true
  values:
    cni:
      image: rancher/mirrored-istio-install-cni:1.9.5
      excludeNamespaces:
        - istio-system
        - kube-system
      logLevel: info
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
```

The docs should be generic about which version to include in the overlay for CNI and say to check that the CNI image version matches your Istio version.
