### ISSUE TITLE
[Rancher2] Missing ClusterRole and ClusterRoleBinding in reference cluster.yml

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/docs#3588]
**Request Summary:**

Cluster Role and Cluster Role Binding is missing from the reference hardened cluster.yml configuration in [v2.6 guide](https://rancher.com/docs/rancher/v2.6/en/security/rancher-2.5/1.6-hardening-2.5/#reference-hardened-rke-cluster-yml-configuration). 
This cluster configuration is present in the [previous guide](https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/1.6-hardening-2.5/#reference-hardened-rke-cluster-yml-configuration).

**Missing cluster configuration:**

Following cluster configuration is missing in v2.6 reference hardened cluster.yml

 ```
apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: psp:restricted
  rules:
  - apiGroups:
    - extensions
    resourceNames:
    - restricted
    resources:
    - podsecuritypolicies
    verbs:
    - use
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: psp:restricted
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: psp:restricted
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:authenticated
```
