### ISSUE TITLE
[Rancher2] Document ingress behavior with cilium CNI

### ISSUE THREAD

**Issue by paynejacob** [rancher/docs#3868]
**Request Summary:**
We should add a section to the rancher 2 docs that explains how to enable cross node ingress routing when selecting the cilium CNI and enabling Project Network Isolation.  By default Cilium does not allow pods to contact pods on other nodes but this can be enabled with a CiliumNetworkPolicy.

```yaml
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: hn-nodes
  namespace: default
spec:
  endpointSelector: {} 
  ingress:
    - fromEntities:
      - remote-node
```
