### ISSUE TITLE
[K3s] Unclear private registry documentation

### ISSUE THREAD

**Issue by adamkpickering** [rancher/docs#3995]
**Request Summary:**

I found the [page explaining private registry configuration](https://rancher.com/docs/k3s/latest/en/installation/private-registry/) confusing. It would help to change some of the examples and perhaps add some explanation so that people don't get confused.

**Details:**

In the [With TLS](https://rancher.com/docs/k3s/latest/en/installation/private-registry/#with-tls) section we have the following example:
```
mirrors:
  docker.io:
    endpoint:
      - "https://mycustomreg.com:5000"
configs:
  "mycustomreg:5000":
    auth:
      username: xxxxxx # this is the registry username
      password: xxxxxx # this is the registry password
    tls:
      cert_file: # path to the cert file used in the registry
      key_file:  # path to the key file used in the registry
      ca_file:   # path to the ca file used in the registry
```
From this, I understand that a mirror, `docker.io`, is being configured. Image names that reference this mirror use the base URL `https://mycustomreg.com:5000` to find and download the images. However, it is not clear to me how the `configs` section applies to the mirror. Presumably this section applies to the `docker.io` mirror, but I don't see anything that references `docker.io` in this section. All we have is `"mycustomreg:5000"`, which doesn't occur anywhere in the `mirrors` section. Was `"mycustomreg:5000"` supposed to be `"mycustomreg.com:5000"`? Or was it supposed to be `docker.io`? Or does it somehow relate to the `mirrors` section in a way I'm not seeing? Or not at all? This is the first point of confusion for me.

The second point of confusion is about the use of the name `docker.io` in the examples. As far as I know, `docker.io` is the default registry. So by defining a `docker.io` mirror in the private registries, are we changing the default registry? If so, this should be described in the docs. If not, perhaps a less confusing name than `docker.io` could be used in the examples.

These comments also apply to the [Without TLS](https://rancher.com/docs/k3s/latest/en/installation/private-registry/#without-tls) section.
