### ISSUE TITLE
Add RKE2 and k3s containerd registry rewrite documentation

### ISSUE THREAD

**Issue by axeal** [rancher/docs#4007]
**Summary:**
The [RKE2 Containerd Registry Configuration documentation](https://docs.rke2.io/install/containerd_registry_configuration/) and the k3s [Private Registry Configuration documentation](https://rancher.com/docs/k3s/latest/en/installation/private-registry/) contain documentation and examples on configuring registry mirrors and registry authentication. They do not however include any documentation or examples on the use of the mirror rewrite functionality, per the following example:
```
mirrors:
  docker.io:
    endpoint:
      - "https://registry.example.com"
    rewrite:
      "^(?:library|)(.*)": "rke-test/docker.io/$1"
```

The request here is to add documentation and an example on the use of the mirror rewrite functionality.
