### ISSUE TITLE
[K3s] Update svclb networkpolicy to account for a recent change

### ISSUE THREAD

**Issue by rancher-max** [rancher/docs#4204]
**Request Summary:**

Update the k3s hardening guide to use a different matchLabel on `allow-all-svclbtraefik-ingress`. This should be valid for previous releases as well, so there shouldn't need to be any additional changes. The networkpolicy yaml in question is in https://rancher.com/docs/k3s/latest/en/security/hardening_guide/#networkpolicies. 

**Details:**

The networkpolicy should be this (which should just be a single change to the value of the `matchLabel`):
```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all-svclbtraefik-ingress
  namespace: kube-system
spec:
  podSelector: 
    matchLabels:
      svccontroller.k3s.cattle.io/svcname: traefik
  ingress:
  - {}
  policyTypes:
  - Ingress
```
