### ISSUE TITLE
Install Guide: Air Gap HA Install

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#614]
https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-installation/ doesn't have instructions for HA in an air gap environment.

**Comment by rawmind0** [comment]
Additionally of instructions showed in the HA docs, for air-gap installation and use private registry images, RKE template needs to be edited as: 

  - adding `private_registries` section

```
private_registries:
  - url: <YOUR_REGISTRY_URL>
    user: <USER>
    password: <PASSWORD>
```

  - Adding `system_images` section accordingly private registry url

```
system_images:
  kubernetes: <YOUR_REGISTRY_URL>/rancher/hyperkube:v1.10.3-rancher2
  etcd: <YOUR_REGISTRY_URL>/rancher/coreos-etcd:v3.1.12
  alpine: <YOUR_REGISTRY_URL>/rancher/rke-tools:v0.1.9
  nginx_proxy: <YOUR_REGISTRY_URL>/rancher/rke-tools:v0.1.9
  cert_downloader: <YOUR_REGISTRY_URL>/rancher/rke-tools:v0.1.9
  kubernetes_services_sidecar: <YOUR_REGISTRY_URL>/rancher/rke-tools:v0.1.9
  kubedns: <YOUR_REGISTRY_URL>/rancher/k8s-dns-kube-dns-amd64:1.14.8
  dnsmasq: <YOUR_REGISTRY_URL>/rancher/k8s-dns-dnsmasq-nanny-amd64:1.14.8
  kubedns_sidecar: <YOUR_REGISTRY_URL>/rancher/k8s-dns-sidecar-amd64:1.14.8
  kubedns_autoscaler: <YOUR_REGISTRY_URL>/rancher/cluster-proportional-autoscaler-amd64:1.0.0
  pod_infra_container: <YOUR_REGISTRY_URL>/rancher/pause-amd64:3.1
  flannel: <YOUR_REGISTRY_URL>/rancher/coreos-flannel:v0.9.1
  flannel_cni: <YOUR_REGISTRY_URL>/rancher/coreos-flannel-cni:v0.2.0
  calico_node: <YOUR_REGISTRY_URL>/rancher/calico-node:v3.1.1
  calico_cni: <YOUR_REGISTRY_URL>/rancher/calico-cni:v3.1.1
  calico_ctl: <YOUR_REGISTRY_URL>/rancher/calico-ctl:v2.0.0
  canal_node: <YOUR_REGISTRY_URL>/rancher/calico-node:v3.1.1
  canal_cni: <YOUR_REGISTRY_URL>/rancher/calico-cni:v3.1.1
  canal_flannel: <YOUR_REGISTRY_URL>/rancher/coreos-flannel:v0.9.1
  ingress: <YOUR_REGISTRY_URL>/rancher/nginx-ingress-controller:0.10.2-rancher3
  ingress_backend: <YOUR_REGISTRY_URL>/rancher/nginx-ingress-controller-defaultbackend:1.4
```

  - modifying `addons` section setting cattle deployment image accordingly private registry url. Optionally, to config private registry as default registry in rancher, add CATTLE_SYSTEM_DEFAULT_REGISTRY env variable.

```
  kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    namespace: cattle-system
    name: cattle
  spec:
    replicas: 1
    template:
      metadata:
        labels:
          app: cattle
      spec:
        serviceAccountName: cattle-admin
        containers:
        - image: <YOUR_REGISTRY_URL>/rancher/rancher:latest
          # Optional to make your registry default rancher registry
          env:
          - name: CATTLE_SYSTEM_DEFAULT_REGISTRY
            value: <YOUR_REGISTRY_URL>
          imagePullPolicy: Always
          name: cattle-server
          ports:
          - containerPort: 80
            protocol: TCP
          - containerPort: 443
            protocol: TCP
          volumeMounts:
          - mountPath: /etc/rancher/ssl
            name: cattle-keys-volume
            readOnly: true
        volumes:
        - name: cattle-keys-volume
          secret:
            defaultMode: 420
            secretName: cattle-keys-server
```
