### ISSUE TITLE
HA RKE Add-on docs improvements

### ISSUE THREAD

**Issue by soumyalj** [rancher/docs#680]
In the HA install link : https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/layer-4-lb/ we provide link to create an RKE template as https://raw.githubusercontent.com/rancher/rancher/7f60dc3afe1b45287ac36ba6bde6f7c6e35c11fe/rke-templates/3-node-externalssl-recognizedca.yml

This template for HA install does not have the etcd backup section which is required when we need to do a backup.
```
services:
  etcd:
    snapshot: true # enables recurring etcd snapshots
    creation: 6h0s # time increment between snapshots
    retention: 24h # time increment before snapshot purge

```
The template should include this in order to do backup/restore
