### ISSUE TITLE
Yaml markdown is improperly formatted.

### ISSUE THREAD

**Issue by jgreat** [rancher/docs#750]
The yaml rendering is aligning the first line with 2 extra spaces and the font is very small.

![image](https://user-images.githubusercontent.com/5324639/45120166-f90a3400-b122-11e8-92be-525327ebbb28.png)

Should look like this:
```yaml
nodes:
- address: 165.227.114.63
  internal_address: 172.16.22.12
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: 165.227.116.167
  internal_address: 172.16.32.37
  user: ubuntu
  role: [controlplane,worker,etcd]
- address: 165.227.127.226
  internal_address: 172.16.42.73
  user: ubuntu
  role: [controlplane,worker,etcd]
```

**Comment by lvuch** [comment]
This is a spacing issue the correct formatting is 4 spaces to indent

correct:
```yaml
nodes:
    - address: 165.227.114.63
      user: ubuntu
      role: [controlplane,worker,etcd]
    - address: 165.227.116.167
      user: ubuntu
      role: [controlplane,worker,etcd]
    - address: 165.227.127.226
      user: ubuntu
      role: [controlplane,worker,etcd]
```

incorrect:
```yaml
nodes:
  - address: 165.227.114.63
    user: ubuntu
    role: [controlplane,worker,etcd]
  - address: 165.227.116.167
    user: ubuntu
    role: [controlplane,worker,etcd]
  - address: 165.227.127.226
    user: ubuntu
    role: [controlplane,worker,etcd]
```
